# Generated by Django 3.0.8 on 2020-07-11 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_contacting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('descreption', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='pics')),
                ('link', models.CharField(max_length=1000)),
            ],
        ),
    ]
